server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/poli/users/**
        - id: movie
          uri: lb://movie
          predicates:
            - Path=/api/v1/poli/movies/**
        - id: booking
          uri: lb://booking
          predicates:
            - Path=/api/v1/poli/bookings/**
        - id: showtime
          uri: lb://showtime
          predicates:
            - Path=/api/v1/poli/showtime/**